services:
  - type: web
    name: weather-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --preload --worker-tmp-dir /dev/shm --log-file -
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      # Add your real API key in the Render dashboard (safer), or put here if you must:
      # - key: OPENWEATHER_API_KEY
      #   value: your-real-key
    healthCheckPath: /health
